# chackout/urls.py
from django.urls import path, include
from .views import(BookingListCreateView, BookingManagementViewSet,
                    FullVehicleBookingViewSet,ManualPaymentViewSet,)
# from .webhook import stripe_webhook
from rest_framework.routers import DefaultRouter
router = DefaultRouter()
router.register(r'admin/bookings', BookingManagementViewSet, basename='admin-booking')
router.register(r'admin/manual-bookings', ManualPaymentViewSet, basename='manual-bookings')

# Get the URLs registered by the router
router_urls = router.get_urls()

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router_urls)),
    
    # Include standard paths
    path("bookings/", BookingListCreateView.as_view(), name="booking-create"),
    path("full-vehicle-booking/", FullVehicleBookingViewSet.as_view({"post": "create"})),
    # path("stripe/webhook/", stripe_webhook, name="stripe-webhook"),
]