# Generated by Django 5.2 on 2025-08-22 08:25

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username may contain letters, numbers, spaces, and @/./+/-/_ characters.', regex='^[\\w.@+\\- ]+$')])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('passenger', 'Passenger')], default='passenger', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('registration_id', models.CharField(max_length=50)),
                ('company_email', models.EmailField(default='', max_length=254)),
                ('contact_number_1', models.CharField(default='', max_length=20)),
                ('contact_number_2', models.CharField(blank=True, max_length=20, null=True)),
                ('company_type', models.CharField(choices=[('offer_vehicle', 'Offer Vehicle'), ('offer_seats', 'Offer Seats')], max_length=20)),
                ('main_office_location', models.CharField(max_length=200)),
                ('owner_name', models.CharField(default='', max_length=150)),
                ('owner_email', models.EmailField(default='', max_length=254)),
                ('owner_contact_number', models.CharField(default='', max_length=20)),
                ('owner_cnic', models.CharField(default='', max_length=20)),
                ('owner_address', models.TextField(default='')),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('registration_id', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_contact_number', models.CharField(default='', max_length=20)),
                ('driver_cnic', models.CharField(default='', max_length=20)),
                ('driving_license_no', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='users.companydetail')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic_or_passport', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(choices=[('Skardu', 'Skardu'), ('Gilgit', 'Gilgit'), ('Shigar', 'Shigar'), ('Hunza', 'Hunza'), ('Nagar', 'Nagar'), ('Khaplu', 'Khaplu'), ('Chilas', 'Chilas'), ('Astor', 'Astor'), ('Islamabad/Rawalpindi', 'Islamabad/Rawalpindi'), ('Gizer', 'Gizer')], max_length=100)),
                ('to_location', models.CharField(choices=[('Skardu', 'Skardu'), ('Gilgit', 'Gilgit'), ('Shigar', 'Shigar'), ('Hunza', 'Hunza'), ('Nagar', 'Nagar'), ('Khaplu', 'Khaplu'), ('Chilas', 'Chilas'), ('Astor', 'Astor'), ('Islamabad/Rawalpindi', 'Islamabad/Rawalpindi'), ('Gizer', 'Gizer')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='users.companydetail')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('coaster', 'Coaster'), ('car', 'Car'), ('hiace', 'Hiace')], max_length=20)),
                ('vehicle_number', models.CharField(default=' ', max_length=50)),
                ('number_of_seats', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.companydetail')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleChoice',
            fields=[
            ],
            options={
                'verbose_name': 'Vehicle Choice',
                'verbose_name_plural': 'Vehicle Choices',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.vehicle',),
        ),
    ]
