# Generated by Django 5.2 on 2025-09-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='Passenger_instruction',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
    ]
