# Generated by Django 5.2 on 2025-10-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companydetail_passenger_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('govt_job', 'Government Job'), ('private_job', 'Private Job'), ('labor_former', 'Labor/Former'), ('business_man', 'Business Man'), ('no_job', 'No Job')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='living_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('unmarried', 'Unmarried')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='notification_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='passenger_profiles/'),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='special_person',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.passengerprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.vehicle')),
            ],
        ),
    ]
