# Generated by Django 5.2 on 2025-11-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passengerprofile_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_driver_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='comment',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_veical_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehical_rate',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
