# Generated by Django 5.2 on 2025-12-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_driver_is_driver_active_vehicle_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='bank_account_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='company_banner',
            field=models.ImageField(blank=True, null=True, upload_to='company_banners/'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='easypaisa_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='easypaisa_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='jazzcash_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='jazzcash_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('ADVANCE', 'Advance Payment Only'), ('CASH', 'Cash Only at Counter'), ('BOTH', 'Both Advance & Cash Payment')], default='BOTH', max_length=20, null=True),
        ),
    ]
