# Generated by Django 5.2 on 2025-09-21 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_cnic', models.CharField(max_length=20)),
                ('passenger_contact', models.CharField(max_length=20)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('seats', models.JSONField(default=list)),
                ('transport_company', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('route_from', models.CharField(max_length=100)),
                ('route_to', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
