# Generated by Django 5.2 on 2025-09-21 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_tickets', '0001_initial'),
        ('transport', '0006_transport_vehicle_seats_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='transport.transport'),
        ),
    ]
