# Generated by Django 5.0.3 on 2025-11-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_remove_booking_ticket'),
        ('passenger_tickets', '0004_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='Payment.booking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Reserved', 'Reserved'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Booked', max_length=20),
        ),
    ]
