# Generated by Django 5.0.3 on 2025-11-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_tickets', '0005_remove_ticket_booking_id_ticket_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
    ]
