# Generated by Django 5.2 on 2025-11-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_tickets', '0006_ticket_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='driver_contect',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('FULLVEHICLE', 'FULLVEHICLE'), ('SEATBOOKING', 'SEATBOOKING')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seats',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
