# Generated by Django 5.0.3 on 2025-11-09 16:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passenger_tickets', '0004_ticket_status'),
        ('users', '0003_passengerprofile_additional_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_full_vehicle', models.BooleanField(default=False, help_text='True if the entire vehicle is booked.')),
                ('seats_booked', models.PositiveIntegerField(default=0, help_text='Number of seats booked (if not full vehicle).')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=5)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, help_text='Time the reservation is held until payment/confirmation.', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.companydetail')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_booking', to='passenger_tickets.ticket')),
                ('user', models.ForeignKey(help_text='The customer who placed the booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text="Typo corrected from 'vachiel'", on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='users.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('STRIPE', 'Stripe')], max_length=20)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('provider_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID or similar external ID.', max_length=255, null=True)),
                ('provider_charge_id', models.CharField(blank=True, help_text='Final charge/transaction ID.', max_length=255, null=True)),
                ('booking', models.OneToOneField(help_text='One-to-one link to the booking this payment satisfies.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_record', to='Payment.booking')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Staff user who confirmed cash receipt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reserved_seats', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(help_text='The absolute time this hold must be released.')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_hold', to='Payment.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for payment, negative for refund.', max_digits=10)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('provider', models.CharField(help_text='e.g., "Stripe", "Cash", "Admin"', max_length=50)),
                ('provider_txn_id', models.CharField(blank=True, help_text='The external ID specific to the provider (e.g., Stripe Charge ID).', max_length=255, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Store raw response data from the provider.')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Payment.booking')),
                ('payment_record', models.ForeignKey(blank=True, help_text='Link to the main Payment record, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='Payment.payment')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff user who initiated/confirmed the transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
