# Generated by Django 5.0.3 on 2025-11-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_booking_seat_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_cnic',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
