# Generated by Django 5.0.3 on 2025-11-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_booking_passenger_cnic_booking_passenger_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
    ]
