# Generated by Django 5.0.3 on 2025-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_remove_booking_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(blank=True, help_text='Scheduled date of arrival/trip start.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Scheduled time of arrival/trip start.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_location',
            field=models.CharField(blank=True, help_text='Starting point of the journey.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_location',
            field=models.CharField(blank=True, help_text='Destination point of the journey.', max_length=255, null=True),
        ),
    ]
