# Generated by Django 5.2 on 2025-12-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_booking_arrival_date_booking_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='User uploaded payment screenshot for manual verification.', null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MANUAL', 'Manual')], max_length=20),
        ),
    ]
