# Generated by Django 5.2 on 2025-09-06 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transport_arrival_date_alter_driver_image_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='users.driver'),
        ),
        migrations.RemoveField(
            model_name='route',
            name='company',
        ),
        migrations.AlterField(
            model_name='transport',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='users.route'),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='company',
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='users.vehicle'),
        ),
        migrations.AddField(
            model_name='transport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to='transports/drivers/'),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='transports/vehicles/'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transport',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
