# Generated by Django 5.2 on 2025-09-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_transport_driver_remove_route_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='offer_type',
            field=models.CharField(choices=[('offer_sets', 'Offer Sets'), ('offer_vehicle', 'Offer Vehicle')], default='offer_sets', max_length=20),
        ),
    ]
