# Generated by Django 5.2 on 2025-09-12 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_transport_offer_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='driver_name_snapshot',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='route_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='route_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_number_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='users.driver'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='users.route'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='users.vehicle'),
        ),
    ]
