# Generated by Django 5.2 on 2025-09-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_transport_driver_name_snapshot_transport_route_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='vehicle_seats_snapshot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='vehicle_type_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
