# Generated by Django 5.2 on 2025-10-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transport_vehicle_seats_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='from_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='is_long_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='is_specific_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='is_taxi_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transport',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='rate_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='to_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='offer_type',
            field=models.CharField(choices=[('offer_sets', 'Offer Sets'), ('whole_hire', 'Whole Vehicle Hire')], default='offer_sets', max_length=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
