# Generated by Django 5.2 on 2025-11-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_transport_from_location_transport_is_long_drive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='driver_contact_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
