# Generated by Django 5.2 on 2025-11-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transport_driver_contact_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='driver_contact_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
