# Generated by Django 5.2 on 2025-11-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_alter_transport_driver_contact_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='is_taxi_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
