# Generated by Django 5.0.3 on 2025-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_alter_transport_is_taxi_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='transport',
            name='is_taxi_service',
        ),
        migrations.AddField(
            model_name='transport',
            name='allow_custom_quote',
            field=models.BooleanField(default=False, help_text='Allow customers to request custom quotes'),
        ),
        migrations.AddField(
            model_name='transport',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated distance in km for specific route', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='fixed_fare',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price for specific route', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this offer is active'),
        ),
        migrations.AddField(
            model_name='transport',
            name='mountain_surcharge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional charge for mountain areas', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='night_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional charge per night', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='per_day_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per day for long drive', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='per_hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rate per hour for long drive', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weekly package rate for long drive', max_digits=10, null=True),
        ),
    ]
